#!/bin/bash

echo "Compiling Ship"
javac -cp asteroidsfw.jar ships/landon/landon.java

echo "Injecting Ship"
jar uf asteroidsfw.jar ships/landon/landon.class

echo "Running Asteroid Game"
java -Djava.library.path=lib/native/macosx -jar asteroidsfw.jar gui=java2d file=input
